version: "3.7"

services:
  api:
    container_name: api.jose-avila.com
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    volumes:
      - ./.env:/app/.env
    ports:
      - 9000:9000
    env_file:
      - .env
